//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication3.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambioPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaPersonaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::WindowsFormsApplication3.Properties.Settings.Default.WindowsFormsApplication3_localhost1_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CambioPersonaCompletedEventHandler CambioPersonaCompleted;
        
        /// <remarks/>
        public event AltaPersonaCompletedEventHandler AltaPersonaCompleted;
        
        /// <remarks/>
        public event BajaPersonaCompletedEventHandler BajaPersonaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CambioPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CambioPersona(int id, string nombre, string apellido_paterno, string apellido_materno, string ci, string telefono, System.DateTime fecha_nacimiento, string direccion, string departamento, string contraseña) {
            object[] results = this.Invoke("CambioPersona", new object[] {
                        id,
                        nombre,
                        apellido_paterno,
                        apellido_materno,
                        ci,
                        telefono,
                        fecha_nacimiento,
                        direccion,
                        departamento,
                        contraseña});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CambioPersonaAsync(int id, string nombre, string apellido_paterno, string apellido_materno, string ci, string telefono, System.DateTime fecha_nacimiento, string direccion, string departamento, string contraseña) {
            this.CambioPersonaAsync(id, nombre, apellido_paterno, apellido_materno, ci, telefono, fecha_nacimiento, direccion, departamento, contraseña, null);
        }
        
        /// <remarks/>
        public void CambioPersonaAsync(int id, string nombre, string apellido_paterno, string apellido_materno, string ci, string telefono, System.DateTime fecha_nacimiento, string direccion, string departamento, string contraseña, object userState) {
            if ((this.CambioPersonaOperationCompleted == null)) {
                this.CambioPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambioPersonaOperationCompleted);
            }
            this.InvokeAsync("CambioPersona", new object[] {
                        id,
                        nombre,
                        apellido_paterno,
                        apellido_materno,
                        ci,
                        telefono,
                        fecha_nacimiento,
                        direccion,
                        departamento,
                        contraseña}, this.CambioPersonaOperationCompleted, userState);
        }
        
        private void OnCambioPersonaOperationCompleted(object arg) {
            if ((this.CambioPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambioPersonaCompleted(this, new CambioPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AltaPersona(int id, string nombre, string apellido_paterno, string apellido_materno, string ci, string telefono, System.DateTime fecha_nacimiento, string direccion, string departamento, string contraseña, int rol) {
            object[] results = this.Invoke("AltaPersona", new object[] {
                        id,
                        nombre,
                        apellido_paterno,
                        apellido_materno,
                        ci,
                        telefono,
                        fecha_nacimiento,
                        direccion,
                        departamento,
                        contraseña,
                        rol});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AltaPersonaAsync(int id, string nombre, string apellido_paterno, string apellido_materno, string ci, string telefono, System.DateTime fecha_nacimiento, string direccion, string departamento, string contraseña, int rol) {
            this.AltaPersonaAsync(id, nombre, apellido_paterno, apellido_materno, ci, telefono, fecha_nacimiento, direccion, departamento, contraseña, rol, null);
        }
        
        /// <remarks/>
        public void AltaPersonaAsync(int id, string nombre, string apellido_paterno, string apellido_materno, string ci, string telefono, System.DateTime fecha_nacimiento, string direccion, string departamento, string contraseña, int rol, object userState) {
            if ((this.AltaPersonaOperationCompleted == null)) {
                this.AltaPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaPersonaOperationCompleted);
            }
            this.InvokeAsync("AltaPersona", new object[] {
                        id,
                        nombre,
                        apellido_paterno,
                        apellido_materno,
                        ci,
                        telefono,
                        fecha_nacimiento,
                        direccion,
                        departamento,
                        contraseña,
                        rol}, this.AltaPersonaOperationCompleted, userState);
        }
        
        private void OnAltaPersonaOperationCompleted(object arg) {
            if ((this.AltaPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaPersonaCompleted(this, new AltaPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BajaPersona(int id) {
            object[] results = this.Invoke("BajaPersona", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BajaPersonaAsync(int id) {
            this.BajaPersonaAsync(id, null);
        }
        
        /// <remarks/>
        public void BajaPersonaAsync(int id, object userState) {
            if ((this.BajaPersonaOperationCompleted == null)) {
                this.BajaPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaPersonaOperationCompleted);
            }
            this.InvokeAsync("BajaPersona", new object[] {
                        id}, this.BajaPersonaOperationCompleted, userState);
        }
        
        private void OnBajaPersonaOperationCompleted(object arg) {
            if ((this.BajaPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaPersonaCompleted(this, new BajaPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CambioPersonaCompletedEventHandler(object sender, CambioPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CambioPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambioPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AltaPersonaCompletedEventHandler(object sender, AltaPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AltaPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AltaPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void BajaPersonaCompletedEventHandler(object sender, BajaPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BajaPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BajaPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591